[package]
name = "srtla_send"
version = "2.0.0"
edition = "2021"
description = "SRT transport proxy with link aggregation for connection bonding (sender-side)"
license = "MIT"
authors = ["Thomas Lekanger <mail@datagutt.no>"]
repository = "https://github.com/irlserver/srtla_send"
homepage = "https://github.com/irlserver/srtla_send"
readme = "README.md"
keywords = ["srt", "streaming", "bonding", "aggregation", "networking"]
categories = ["network-programming", "multimedia"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
rand = "0.9"
tokio = { version = "1.47.1", features = [
	"rt-multi-thread",
	"macros",
	"net",
	"time",
	"io-util",
	"signal",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
socket2 = { version = "0.6", features = ["all"] }
bytes = "1.10.1"
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
